### ISSUE TITLE
Factions ToDo List Backlog

### ISSUE THREAD

**Issue by Mike-MF** [Theseus-Aegis/Units#134]
**Backlog:**
- [ ] **South American Expansion:**
    - [ ] **South American Cartel:**
        - Follow same idea the original cartel, create south american faces with Tattoos.
        - Custom textures for vehicles. 
    - [ ] **South American Rebels:**
        - Small-scale, low geared rebel types. Utilising faces made for south america. 
    - [ ] **South American Military:**
        - Bordering on Militia, small-scale military. 
- [ ] **Russian Mafia** (Bratva)
     - Organised crime group, small-scale gangster types.
     - More tattoos/custom identities.
- [ ] **Children of Chernobog**
    - Wearing anything.
    - Based on Alans wild ass mission with tin foil hats
- [ ] UNA Expansion (WS)
    - UNA = United Assistance, expand for areas outside of Desert.
