### ISSUE TITLE
2.0.0 Factions ToDo List

### ISSUE THREAD

**Issue by Mike-MF** [Theseus-Aegis/Units#68]
**v2.0.0:**
- [x] **Northern Africa**
	- #79
- [x] **African Militia:**
	- #101
- [x] **British Armed Forces:**
	- #71
- [x] **Proxy China**
	-  #123
- [x] **Proxy Russia**
	- #102
- [x] **Eastern Asia**
	- #123
- [x] **French Foreign Legion:**
	- #120
- [x] **Somali Pirates:**
    - #81
- [x] **Southern Africa:**
    - #99
- [x] **Taliban**
    - #83
- [x] **Seven Rings Rework**
    - #95
- [x] **Eastern Europeans:**
    - #102 
    - #125 

**Dropped:**
- ~~CTRG Expansion~~ 
- ~~CSAT Expansion:~~
