### ISSUE TITLE
ToDo List for Rebranding

### ISSUE THREAD

**Issue by Mike-MF** [Theseus-Aegis/Units#94]
- [ ] Move `requiredAddons` to each individual component.
- [ ] Make use of Arma 2.14s `skipWhenMissingDependencies`
- [ ] Rework Seven Rings to use completely Vanilla assets.
- [ ] Move CUP Turrets back to it's own component and add them to factions there?
- [ ] Decide on "Core" dependencies
    - CBA
    - Theseus Services
    - ACE?

**Comment by Mike-MF** [comment]
Decided it's too much work, isn't happening.
